# Generated by Django 5.2.4 on 2025-09-04 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the medical record was created')),
                ('patient_id', models.CharField(help_text='Unique identifier for the patient', max_length=100)),
                ('doctor_id', models.CharField(help_text='Unique identifier for the doctor', max_length=100)),
                ('content', models.TextField(help_text='Medical record content and notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('doctor_user', models.ForeignKey(blank=True, help_text='Django User object for the doctor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-datetime', '-created_at'],
                'indexes': [models.Index(fields=['patient_id'], name='dashboard_m_patient_e0a53a_idx'), models.Index(fields=['doctor_id'], name='dashboard_m_doctor__97fd2f_idx'), models.Index(fields=['datetime'], name='dashboard_m_datetim_6d78e4_idx')],
            },
        ),
    ]
