# Generated by Django 5.2.4 on 2025-09-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_doctor_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the appointment in minutes')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('checkup', 'Check-up'), ('emergency', 'Emergency'), ('procedure', 'Procedure'), ('therapy', 'Therapy'), ('other', 'Other')], default='consultation', help_text='Type of appointment', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the appointment', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the appointment', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the appointment', null=True)),
                ('location', models.CharField(blank=True, help_text='Location of the appointment (room, clinic, etc.)', max_length=200, null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder has been sent')),
                ('reminder_date', models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this appointment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this appointment was last updated')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the appointment was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('doctor', models.ForeignKey(help_text='Doctor for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dashboard.doctor')),
                ('patient', models.ForeignKey(help_text='Patient for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dashboard.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='dashboard_a_appoint_abaf0a_idx'), models.Index(fields=['patient'], name='dashboard_a_patient_3b1620_idx'), models.Index(fields=['doctor'], name='dashboard_a_doctor__ff8c4e_idx'), models.Index(fields=['status'], name='dashboard_a_status_9daa2b_idx'), models.Index(fields=['appointment_type'], name='dashboard_a_appoint_6500a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_doctor_appointment_time')],
            },
        ),
    ]
