# Generated by Django 5.2.4 on 2025-09-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='legacy_doctor_id',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='legacy_patient_id',
        ),
    ]
