# Generated by Django 5.2.4 on 2025-09-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_medicalrecord_legacy_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Retorno'), ('checkup', 'Check-up'), ('emergency', 'Emergência'), ('procedure', 'Procedimento'), ('therapy', 'Terapia'), ('other', 'Outro')], default='consultation', help_text='Type of appointment', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('no_show', 'Não Compareceu'), ('rescheduled', 'Reagendada')], default='scheduled', help_text='Current status of the appointment', max_length=20),
        ),
    ]
