# Generated by Django 5.2.4 on 2025-09-23 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the prescription template', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the prescription template', null=True)),
                ('header_text', models.TextField(blank=True, help_text='Header text for the prescription', null=True)),
                ('footer_text', models.TextField(blank=True, help_text='Footer text for the prescription', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_templates', to='dashboard.doctor')),
            ],
            options={
                'verbose_name': 'Prescription Template',
                'verbose_name_plural': 'Prescription Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the prescription was created')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', help_text='Current status of the prescription', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the prescription', null=True)),
                ('sent_by_email', models.BooleanField(default=False, help_text='Whether prescription was sent by email')),
                ('sent_by_whatsapp', models.BooleanField(default=False, help_text='Whether prescription was sent by WhatsApp')),
                ('printed', models.BooleanField(default=False, help_text='Whether prescription was printed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor who prescribed this medication', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dashboard.doctor')),
                ('patient', models.ForeignKey(help_text='Patient for this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dashboard.patient')),
                ('template', models.ForeignKey(blank=True, help_text='Prescription template used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='dashboard.prescriptiontemplate')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescription_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Name of the medication', max_length=200)),
                ('quantity', models.CharField(help_text="Quantity of the medication (e.g., '30 comprimidos', '1 frasco')", max_length=100)),
                ('dosage', models.TextField(help_text="Dosage instructions (e.g., '1 comprimido de 8/8 horas')")),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this medication', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this item in the prescription')),
                ('prescription', models.ForeignKey(help_text='Prescription this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['prescription'], name='dashboard_p_prescri_c2cf01_idx'), models.Index(fields=['order'], name='dashboard_p_order_80ad6c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='dashboard_p_patient_08e312_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor'], name='dashboard_p_doctor__dce7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_date'], name='dashboard_p_prescri_4a1fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='dashboard_p_status_45c30f_idx'),
        ),
    ]
