# Generated by Django 5.2.4 on 2025-10-01 22:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_prescriptiontemplate_prescription_prescriptionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the expense', max_digits=10)),
                ('description', models.CharField(help_text='Description of the expense', max_length=200)),
                ('category', models.CharField(choices=[('office_supplies', 'Material de Escritório'), ('medical_supplies', 'Material Médico'), ('equipment', 'Equipamentos'), ('utilities', 'Utilidades'), ('rent', 'Aluguel'), ('insurance', 'Seguro'), ('marketing', 'Marketing'), ('professional_services', 'Serviços Profissionais'), ('travel', 'Viagens'), ('education', 'Educação'), ('other', 'Outros')], help_text='Category of the expense', max_length=30)),
                ('expense_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the expense was made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the expense', null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt or invoice number', max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, help_text='Vendor or supplier name', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor who made this expense', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dashboard.doctor')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['doctor'], name='dashboard_e_doctor__bba4af_idx'), models.Index(fields=['expense_date'], name='dashboard_e_expense_3c31a3_idx'), models.Index(fields=['category'], name='dashboard_e_categor_5a3e9b_idx')],
            },
        ),
    ]
