# Generated by Django 5.2.4 on 2025-10-03 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value/price of the appointment', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the income', max_digits=10)),
                ('description', models.CharField(help_text='Description of the income', max_length=200)),
                ('category', models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Retorno'), ('checkup', 'Check-up'), ('emergency', 'Emergência'), ('procedure', 'Procedimento'), ('therapy', 'Terapia'), ('other', 'Outros')], help_text='Category of the income', max_length=30)),
                ('income_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the income was received')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the income', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (cash, card, transfer, etc.)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Appointment that generated this income', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='dashboard.appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor who received this income', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='dashboard.doctor')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'ordering': ['-income_date', '-created_at'],
                'indexes': [models.Index(fields=['doctor'], name='dashboard_i_doctor__620123_idx'), models.Index(fields=['income_date'], name='dashboard_i_income__0175ad_idx'), models.Index(fields=['category'], name='dashboard_i_categor_97ccab_idx')],
            },
        ),
    ]
