# Generated by Django 5.2.4 on 2025-10-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_appointment_value_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('pix', 'PIX'), ('other', 'Outros')], help_text='Payment method', max_length=20, null=True),
        ),
    ]
