# Generated by Django 5.2.4 on 2025-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_income_payment_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_time',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'confirmed', 'in_progress', 'completed', 'no_show', 'rescheduled'])), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_doctor_appointment_time'),
        ),
    ]
