# Generated by Django 5.2.4 on 2025-10-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_update_appointment_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_type',
            field=models.CharField(choices=[('convenio', 'Convênio'), ('particular', 'Particular')], default='particular', help_text='Payment type for the appointment', max_length=20),
        ),
    ]
