# Generated by Django 5.2.4 on 2025-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_appointment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the patient is currently active'),
        ),
    ]
