# Generated by Django 5.2.4 on 2025-10-27 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_patient_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text="Secretary's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the secretary is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this secretary profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this secretary profile was last updated')),
            ],
            options={
                'verbose_name': 'Secretary',
                'verbose_name_plural': 'Secretaries',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text="Admin's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the admin is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this admin profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this admin profile was last updated')),
                ('user', models.OneToOneField(help_text='Django User object for the admin', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin who manages this doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='dashboard.admin'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['admin'], name='dashboard_d_admin_i_0f9130_idx'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor this secretary works for', on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to='dashboard.doctor'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='user',
            field=models.OneToOneField(help_text='Django User object for the secretary', on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['is_active'], name='dashboard_a_is_acti_bb47f8_idx'),
        ),
        migrations.AddIndex(
            model_name='secretary',
            index=models.Index(fields=['doctor'], name='dashboard_s_doctor__cc84e4_idx'),
        ),
        migrations.AddIndex(
            model_name='secretary',
            index=models.Index(fields=['is_active'], name='dashboard_s_is_acti_b599c0_idx'),
        ),
    ]
