# Generated by Django 5.2.4 on 2025-10-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_secretary_admin_doctor_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who manages this patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='dashboard.doctor'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['doctor'], name='dashboard_p_doctor__c18516_idx'),
        ),
    ]
