# Generated by Django 5.2.4 on 2025-12-02 01:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text="Patient's full name", max_length=200)),
                ('phone', models.CharField(blank=True, help_text="Patient's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text="Patient's email address", max_length=254, null=True)),
                ('preferred_days_times', models.TextField(blank=True, help_text="Preferred days and times for appointment (e.g., 'Monday mornings, Wednesday afternoons')", null=True)),
                ('urgency_level', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Urgency level of the appointment request', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendada'), ('archived', 'Arquivada')], default='pending', help_text='Current status of the waitlist entry', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the patient or appointment request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this entry was added to the waitlist')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this entry was last updated')),
                ('doctor', models.ForeignKey(help_text='Doctor who manages this waitlist entry', on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='dashboard.doctor')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient record if exists in system (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_list_entries', to='dashboard.patient')),
            ],
            options={
                'verbose_name': 'Waiting List Entry',
                'verbose_name_plural': 'Waiting List Entries',
                'ordering': ['-urgency_level', 'created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='dashboard_w_doctor__05c971_idx'), models.Index(fields=['urgency_level', 'created_at'], name='dashboard_w_urgency_86516c_idx'), models.Index(fields=['status'], name='dashboard_w_status_fe4a03_idx')],
            },
        ),
    ]
