# Generated by Django 5.2.4 on 2025-12-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_waitinglistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_options', models.JSONField(default=list, help_text='Available duration options in minutes (e.g., [15, 30, 45, 60, 90, 120])')),
                ('type_choices', models.JSONField(default=list, help_text='Available appointment types as [value, label] pairs')),
                ('status_choices', models.JSONField(default=list, help_text='Available appointment statuses as [value, label] pairs')),
                ('location_options', models.JSONField(default=list, help_text='Available location/place options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Settings',
                'verbose_name_plural': 'Appointment Settings',
            },
        ),
    ]
