# Generated by Django 5.2.4 on 2025-12-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_migrate_settings_to_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsettings',
            name='status_colors',
            field=models.JSONField(default=dict, help_text="Color mapping for each status (e.g., {'Agendada': '#007bff', 'Confirmada': '#28a745'})"),
        ),
        migrations.AlterField(
            model_name='appointmentsettings',
            name='status_choices',
            field=models.JSONField(default=list, help_text='Available appointment statuses as display names'),
        ),
        migrations.AlterField(
            model_name='appointmentsettings',
            name='type_choices',
            field=models.JSONField(default=list, help_text='Available appointment types as display names'),
        ),
    ]
