# Generated by Django 5.2.4 on 2025-12-16 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_add_status_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient related to this income', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='dashboard.patient'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['patient'], name='dashboard_i_patient_14b74d_idx'),
        ),
    ]
