# Generated by Django 5.2.4 on 2025-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_add_patient_to_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='insurance_operator',
            field=models.CharField(blank=True, help_text='Insurance operator (convênio) when payment type is convenio', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsettings',
            name='insurance_operators',
            field=models.JSONField(default=list, help_text='Available insurance operators (convênios) as display names'),
        ),
    ]
