# Generated by Django 5.2.4 on 2025-12-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_appointment_insurance_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsettings',
            name='cancellation_reasons',
            field=models.JSONField(default=list, help_text='Available cancellation reasons as display names'),
        ),
    ]
