# Generated by Django 5.2.4 on 2026-01-28 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_add_cancellation_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp phone number', max_length=20)),
                ('state', models.CharField(choices=[('initial', 'Inicial'), ('selecting_doctor', 'Selecionando Médico'), ('selecting_date', 'Selecionando Data'), ('selecting_time', 'Selecionando Horário'), ('collecting_patient_info', 'Coletando Informações do Paciente'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='initial', help_text='Current conversation state', max_length=30)),
                ('selected_date', models.DateField(blank=True, help_text='Selected appointment date', null=True)),
                ('selected_time', models.TimeField(blank=True, help_text='Selected appointment time', null=True)),
                ('patient_name', models.CharField(blank=True, help_text='Patient name from conversation', max_length=200, null=True)),
                ('patient_phone', models.CharField(blank=True, help_text='Patient phone number', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When conversation started')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When conversation was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When conversation was completed', null=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Created appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversation', to='dashboard.appointment')),
                ('selected_doctor', models.ForeignKey(blank=True, help_text='Selected doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='dashboard.doctor')),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
                'verbose_name_plural': 'WhatsApp Conversations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['phone_number'], name='dashboard_w_phone_n_ef5a8a_idx'), models.Index(fields=['state'], name='dashboard_w_state_fdf4f2_idx'), models.Index(fields=['created_at'], name='dashboard_w_created_8e2951_idx')],
            },
        ),
    ]
