# Generated by Django 5.2.4 on 2026-02-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_whatsappconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, help_text="Patient's CPF (Brazilian tax ID)", max_length=14, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['cpf'], name='dashboard_p_cpf_7e5803_idx'),
        ),
    ]
