# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_patient_cpf_patient_dashboard_p_cpf_7e5803_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsettings',
            name='convenio_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default value/price for convenio appointments', max_digits=10),
        ),
    ]
