# Generated by Django - one price per convenio (operator)

from django.db import migrations, models


def migrate_convenio_price_to_prices(apps, schema_editor):
    """Copy single convenio_price to convenio_prices dict for each operator."""
    AppointmentSettings = apps.get_model('dashboard', 'AppointmentSettings')
    for s in AppointmentSettings.objects.all():
        price_str = str(s.convenio_price) if s.convenio_price is not None else '0'
        s.convenio_prices = {op: price_str for op in (s.insurance_operators or [])}
        s.save(update_fields=['convenio_prices'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_add_convenio_price_to_appointment_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsettings',
            name='convenio_prices',
            field=models.JSONField(default=dict, help_text='Price per insurance operator: {operator_name: price_string}'),
        ),
        migrations.RunPython(migrate_convenio_price_to_prices, noop_reverse),
        migrations.RemoveField(
            model_name='appointmentsettings',
            name='convenio_price',
        ),
    ]
