# Generated by Django 5.2.4 on 2026-02-23 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_add_no_show_to_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Start of blocked period')),
                ('end', models.DateTimeField(help_text='End of blocked period')),
                ('reason', models.CharField(blank=True, help_text='Optional reason (e.g. Folga, Congresso)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(help_text='Doctor whose calendar is blocked', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to='dashboard.doctor')),
            ],
            options={
                'verbose_name': 'Calendar Block',
                'verbose_name_plural': 'Calendar Blocks',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['doctor'], name='dashboard_c_doctor__601420_idx'), models.Index(fields=['start', 'end'], name='dashboard_c_start_5929b9_idx')],
            },
        ),
    ]
