# Generated by Django 5.2.4 on 2026-02-23 00:45
# Edit: add M2M first, keep FK for data migration in 0031

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_calendar_block'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='dashboard_d_admin_i_0f9130_idx',
        ),
        migrations.RemoveIndex(
            model_name='secretary',
            name='dashboard_s_doctor__cc84e4_idx',
        ),
        migrations.AddField(
            model_name='doctor',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admins who manage this doctor', related_name='doctors', to='dashboard.admin'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='doctors',
            field=models.ManyToManyField(blank=True, help_text='Doctors this secretary works for', related_name='secretaries', to='dashboard.doctor'),
        ),
    ]
