# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_m2m_data_and_remove_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Pergunta ou título', max_length=500)),
                ('answer', models.TextField(help_text='Resposta da base de conhecimento')),
                ('keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula para busca', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Base de Conhecimento (FAQ)',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Dados do fluxo: search_type, search_results, selected_slot, faq_answer, etc.'),
        ),
    ]
