# Generated by Django 5.2.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_faqentry_whatsapp_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='patient',
            field=models.ForeignKey(
                blank=True,
                help_text='Patient identified by CPF or registered at chat start',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='whatsapp_conversations',
                to='dashboard.patient',
            ),
        ),
    ]
