# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_whatsappconversation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsettings',
            name='whatsapp_clinic_message',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Mensagem da clínica enviada ao encerrar o atendimento no WhatsApp (deixe em branco para não enviar)',
            ),
        ),
    ]
