# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_appointmentsettings_whatsapp_clinic_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsettings',
            name='whatsapp_clinic_message',
        ),
    ]
