# Generated by Django 5.2.4 on 2026-03-20 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_appointmentsettings_whatsapp_clinic_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Clinic name', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Clinic phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Clinic email address', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Clinic address', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the clinic is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='admins',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='dashboard_p_doctor__c18516_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_clinic_admin',
            field=models.BooleanField(default=False, help_text='Whether this doctor also acts as a clinic administrator'),
        ),
        migrations.AlterField(
            model_name='whatsappconversation',
            name='state',
            field=models.CharField(choices=[('initial', 'Inicial'), ('channel_choice', 'Escolha de Canal (Texto/Ligação)'), ('patient_cpf', 'Identificação por CPF'), ('patient_register_name', 'Cadastro do paciente - nome'), ('patient_register_phone', 'Cadastro do paciente - telefone'), ('patient_register_gender', 'Cadastro do paciente - sexo'), ('patient_register_birth', 'Cadastro do paciente - data nascimento'), ('schedule_payment_type', 'Tipo de pagamento (particular/seguro)'), ('schedule_select_insurance', 'Seleção de convênio/seguro'), ('schedule_confirm_final', 'Confirmação final do agendamento'), ('consult_cpf', 'Consultar/Desmarcar - CPF'), ('consult_list', 'Consultar/Desmarcar - lista'), ('consult_cancel_select', 'Consultar/Desmarcar - escolher qual desmarcar'), ('consult_cancel_confirm', 'Consultar/Desmarcar - confirmar desmarque'), ('main_menu', 'Menu Principal'), ('schedule_alert', 'Alerta LGPD Agendamento'), ('schedule_search_type', 'Tipo de Busca Agendamento'), ('schedule_search_name', 'Busca por Nome'), ('schedule_search_specialty', 'Busca por Especialidade'), ('schedule_search_date', 'Busca por Data/Unidade'), ('schedule_select_doctor', 'Escolha do Profissional (lista numerada)'), ('schedule_select_date', 'Informar melhor data'), ('schedule_list', 'Seleção de Horário/Profissional'), ('schedule_confirm', 'Confirmação Agendamento'), ('schedule_collecting_patient', 'Dados do Paciente'), ('selecting_doctor', 'Selecionando Médico'), ('selecting_date', 'Selecionando Data'), ('selecting_time', 'Selecionando Horário'), ('collecting_patient_info', 'Coletando Informações do Paciente'), ('faq_question', 'Dúvida/FAQ'), ('faq_resolved', 'Dúvida Resolvida?'), ('loop_desire_more', 'Deseja algo mais?'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('ended', 'Encerrada')], default='initial', help_text='Current conversation state', max_length=30),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='dashboard_c_name_c2724d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='dashboard_c_is_acti_2980a4_idx'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic this doctor belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='dashboard.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic this patient belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='dashboard.clinic'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic this secretary belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='dashboard.clinic'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic'], name='dashboard_p_clinic__3129c4_idx'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
