# Generated by Django 5.2.4 on 2026-03-20 13:47

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_clinic_structure_remove_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file (image or PDF)', upload_to=dashboard.models.patient_file_upload_to)),
                ('original_name', models.CharField(help_text='Original filename as uploaded by the user', max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Imagem'), ('pdf', 'PDF'), ('other', 'Outro')], default='other', help_text='Detected file type', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this file', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Doctor who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_files', to='dashboard.doctor')),
            ],
            options={
                'verbose_name': 'Patient File',
                'verbose_name_plural': 'Patient Files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='dashboard_p_patient_218ae4_idx'), models.Index(fields=['uploaded_by'], name='dashboard_p_uploade_3bdfd0_idx'), models.Index(fields=['file_type'], name='dashboard_p_file_ty_cb0223_idx')],
            },
        ),
    ]
