# Generated by Django 5.2.4 on 2026-03-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_add_patient_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='Systolic pressure (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='Diastolic pressure (mmHg)', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate (bpm)', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Respiratory rate (rpm)', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature (°C)', max_digits=4, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO₂ (%)', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg)', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height (cm)', max_digits=5, null=True)),
                ('chief_complaint', models.TextField(blank=True, help_text='Queixa Principal', null=True)),
                ('hda', models.TextField(blank=True, help_text='História da Doença Atual (HDA)', null=True)),
                ('past_history', models.TextField(blank=True, help_text='Antecedentes pessoais e familiares', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Alergias e reações adversas', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Medicamentos em uso', null=True)),
                ('systems_review', models.TextField(blank=True, help_text='Revisão de sistemas', null=True)),
                ('physical_exam', models.TextField(blank=True, help_text='Exame Físico', null=True)),
                ('diagnostic_hypothesis', models.TextField(blank=True, help_text='Hipótese Diagnóstica', null=True)),
                ('cid10_code', models.CharField(blank=True, help_text='Código CID-10', max_length=10, null=True)),
                ('cid10_description', models.CharField(blank=True, help_text='Descrição CID-10', max_length=300, null=True)),
                ('conduct', models.TextField(blank=True, help_text='Conduta e Plano Terapêutico', null=True)),
                ('exam_requests', models.TextField(blank=True, help_text='Solicitação de Exames e Procedimentos', null=True)),
                ('return_instructions', models.TextField(blank=True, help_text='Orientações de retorno', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the consultation was started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the consultation was concluded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(help_text='Appointment this consultation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='consultation_record', to='dashboard.appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor conducting the consultation', on_delete=django.db.models.deletion.CASCADE, related_name='consultation_records', to='dashboard.doctor')),
                ('patient', models.ForeignKey(help_text='Patient being consulted', on_delete=django.db.models.deletion.CASCADE, related_name='consultation_records', to='dashboard.patient')),
            ],
            options={
                'verbose_name': 'Consultation Record',
                'verbose_name_plural': 'Consultation Records',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['appointment'], name='dashboard_c_appoint_ada81c_idx'), models.Index(fields=['patient'], name='dashboard_c_patient_d88eb6_idx'), models.Index(fields=['doctor'], name='dashboard_c_doctor__669bef_idx')],
            },
        ),
    ]
