# Generated by Django 5.2.4 on 2026-04-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_appointmentsettings_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='custom_expense_categories',
            field=models.JSONField(blank=True, default=list, help_text='Custom expense categories defined by this doctor'),
        ),
        migrations.AddField(
            model_name='income',
            name='is_free_return',
            field=models.BooleanField(default=False, help_text='Mark as a free return visit (retorno gratuito) — amount treated as R$ 0,00'),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('particular', 'Particular'), ('convenio', 'Convênio')], help_text='Whether payment is private (particular) or via health plan (convenio)', max_length=20, null=True),
        ),
    ]
