# Generated by Django 5.2.4 on 2026-04-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_doctor_custom_expense_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='transcription',
            field=models.TextField(blank=True, help_text='Real-time transcription from Whisper Server', null=True),
        ),
    ]
