# Generated by Django 5.2.4 on 2026-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_consultationrecord_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsettings',
            name='churn_risk_months',
            field=models.PositiveIntegerField(default=6, help_text="Number of months without a visit to consider a patient 'At Risk'"),
        ),
        migrations.AddField(
            model_name='appointmentsettings',
            name='churn_threshold_months',
            field=models.PositiveIntegerField(default=12, help_text="Number of months without a visit to consider a patient as 'Churn'"),
        ),
    ]
