# Generated by Django 5.2.4 on 2025-10-27 19:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0012_patient_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text="Secretary's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the secretary is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this secretary profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this secretary profile was last updated')),
                ('doctor', models.ForeignKey(help_text='Doctor this secretary works for', on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to='dashboard.doctor')),
                ('user', models.OneToOneField(help_text='Django User object for the secretary', on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secretary',
                'verbose_name_plural': 'Secretaries',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['doctor'], name='accounts_se_doctor__def707_idx'), models.Index(fields=['is_active'], name='accounts_se_is_acti_a7b0d1_idx')],
            },
        ),
    ]
